mainApp/urls.py
from django.urls import path

from . import views

app_name = 'mainApp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('addTutorial/', views.add_new_tutorial, name='addTutorial'),
    path('addCategory/', views.add_new_tutorial_category, name='addCategory'),
    path('addSeries/', views.add_new_tutorial_series, name='addSeries'),
    path('search/', views.search, name='search'),
    path('<single_slug>', views.single_slug, name='single_slug'),
]

mainApp/models.py
from django.db import models
from datetime import datetime
# Create your models here.
# a model is creating a table in your database. So for each table one model class

class TutorialCategory(models.Model):
    tutorial_category = models.CharField(max_length=200)
    category_summary = models.CharField(max_length=200)
    category_slug = models.CharField(max_length=200, default=1)

    class Meta:
        # Gives the proper plural name for admin
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.tutorial_category

class TutorialSeries(models.Model):
    tutorial_series = models.CharField(max_length=200)
    series_summary = models.CharField(max_length=200)
    
    tutorial_category = models.ForeignKey(TutorialCategory,
                            default=1,
                            verbose_name="Category",
                            on_delete=models.SET_DEFAULT)
    

    class Meta:
        # otherwise we get "Tutorial Seriess in admin"
        verbose_name_plural = "Series"

    def __str__(self) -> str:
        return self.tutorial_series

class Tutorial(models.Model):
    tutorial_title = models.CharField(max_length=200)
    tutorial_content = models.TextField() 
    tutorial_published = models.DateTimeField('date published', default=datetime.now())

    tutorial_series = models.ForeignKey(TutorialSeries,
                            default=1,
                            verbose_name="Series",
                            on_delete=models.SET_DEFAULT)    

    tutorial_slug = models.CharField(max_length=200, default=1)

    def __str__(self) -> str:
        return self.tutorial_title

mainApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Tutorial, TutorialSeries, TutorialCategory

"""
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2",)

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
"""

class TutorialForm(forms.Form):    # We extends forms.ModelForm for easy form
    """
    tutorial_slug = forms.CharField(help_text="slug is a unique identifier for the tutorial")
    tutorial_content = forms.CharField(widget=TinyMCE(mce_attrs={'width': 100})
     )

    class Meta:
        model = Tutorial
        fields = ("tutorial_title", "tutorial_series", "tutorial_slug", "tutorial_content")
        
    """ 
    
    SERIES_CHOICES = [(obj , obj) for obj in TutorialSeries.objects.all()]
    title = forms.CharField()
    linked_series = forms.ChoiceField(choices=SERIES_CHOICES)
    content = forms.CharField()
    slug= forms.CharField(help_text='slug is a unique identifier for this tutorial')

    class Meta:
        model = Tutorial
        fields = ("tutorial_title", "tutorial_series", "tutorial_slug", "tutorial_content")


    def save(self, commit=True):
        
        tutorial = Tutorial()  #super(TutorialForm, self)
        tutorial.tutorial_title = self.cleaned_data["title"]
        # this filtering is needed because the choiceField is returning string and we need object
        tutorial.tutorial_series = TutorialSeries.objects.filter(tutorial_series = self.cleaned_data['linked_series'])[0]
        tutorial.tutorial_content = self.cleaned_data["content"]
        tutorial.tutorial_slug = self.cleaned_data["slug"]
        if commit:
            tutorial.save()
        return tutorial
    

class TutorialCategoryForm(forms.ModelForm):
    category_slug = forms.CharField(help_text="slug is a unique identifier for the category. It will be used for category url")

    class Meta:
        model = TutorialCategory
        fields = '__all__'


class TutorialSeriesForm(forms.ModelForm):

    class Meta:
        model = TutorialSeries
        fields = '__all__'

mainApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Tutorial, TutorialCategory, TutorialSeries
from django.db.models import Q
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import  TutorialForm, TutorialCategoryForm, TutorialSeriesForm
from django.contrib import messages
# Create your views here.
#A view function for a page
"""
def homepage(request):
    return HttpResponse('Hello you have started <strong>learning</strong> django framwork!!')
"""
#def single_slug()
def single_slug(request, single_slug):
    # first check to see if the url is in categories.

    categories = [c.category_slug for c in TutorialCategory.objects.all()]
    if single_slug in categories:
        matching_series = TutorialSeries.objects.filter(tutorial_category__category_slug=single_slug)
        series_urls = {}

        for m in matching_series.all():
            part_one = Tutorial.objects.filter(tutorial_series__tutorial_series=m.tutorial_series).earliest("tutorial_published")
            series_urls[m] = part_one.tutorial_slug

        return render(request=request,
                      template_name='mainApp/category.html',
                      context={"tutorial_series": matching_series, "part_ones": series_urls})

    tutorials = [t.tutorial_slug for t in Tutorial.objects.all()]
    if single_slug in tutorials:
        this_tutorial = Tutorial.objects.get(tutorial_slug = single_slug)
        tutorials_from_series = Tutorial.objects.filter(tutorial_series__tutorial_series = 
                                                this_tutorial.tutorial_series).order_by('tutorial_published')
        this_tutorial_index = list(tutorials_from_series).index(this_tutorial)

        return render(request,
                      template_name="mainApp/tutorial.html",
                      context={"tutorial":this_tutorial,
                               "sidebar": tutorials_from_series,
                               "this_tut_idx": this_tutorial_index}
        )

    return HttpResponse(f"'{single_slug}' does not correspond to anything we know of!")




def homepage(request):
    return render(request=request,
                template_name="mainApp/home.html",
                context={"categories": TutorialCategory.objects.all})


def add_new_tutorial(request):

    if request.method == "POST":
        form = TutorialForm(request.POST)
        if form.is_valid():
            tutorial = form.save()
            messages.info(request, f"Your tutorial #{tutorial.tutorial_title} is added")
            return redirect("mainApp:homepage")
        else:
            for msg in form.errors:
                messages.error(request, f"{msg}: {form.errors[msg]}")

    form = TutorialForm
    return render(request=request,
                template_name="mainApp/inputForms/addTutorial.html",
                context={"form": form }) 


def add_new_tutorial_category(request):

    if request.method == "POST":
        form = TutorialCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, f"Your tutorial Category is added")
            return redirect("mainApp:homepage")
        else:
            for msg in form.errors:
                messages.error(request, f"{msg}: {form.errors[msg]}")

    form = TutorialCategoryForm
    return render(request=request,
                template_name="mainApp/inputForms/addCategory.html",
                context={"form": form }) 


def add_new_tutorial_series(request):

    if request.method == "POST":
        form = TutorialSeriesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, f"Your tutorial series is added")
            return redirect("mainApp:homepage")
        else:
            for msg in form.errors:
                messages.error(request, f"{msg}: {form.errors[msg]}")

    form = TutorialSeriesForm
    return render(request=request,
                template_name="mainApp/inputForms/addSeries.html",
                context={"form": form }) 


def register(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Accoutn created successfully: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as: {username}")
            return redirect("mainApp:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")


    form = UserCreationForm
    return render(request=request,
                template_name="mainApp/register.html",
                context={"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully")
    return redirect("mainApp:homepage")


def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as: {username}")
                return redirect("mainApp:homepage")
            else:
                messages.error(request, f"Try again with a valid user credentials")
        else:
                messages.error(request, f"Try again with a valid user credentials")

    form = AuthenticationForm()
    return render(request=request,
                template_name="mainApp/login.html",
                context={"form":form})


def search(request):

    if request.method == "GET":
        query = request.GET.get('q')
        submitbutton = request.GET.get('submit')
        submitbutton = 'Search' # will be used if any search button is placed
        if query is not None:
            # create a custom lookup to be used for filter
            lookups = Q(tutorial_title__icontains=query) | Q(tutorial_content__icontains=query)
            results = Tutorial.objects.filter(lookups).distinct()
            # send matching objects to result page
            context={'results': results,
                     'submitbutton': submitbutton}
            if len(results)>0:
                messages.info(request, f"List of matched Tutorials")
            else:
                messages.warning(request, f"No results with searched title")
            return render(request,
                        template_name="mainApp/search.html",
                        context=context)
        else:
            messages.error(request, f"Provide a query to search")
            return render(request,
                        template_name="mainApp/search.html",)
    else:
        return render(request,
                        template_name="mainApp/search.html",)

mainApp/templates/mainApp/includes/categories.html
{% load static %}

<div class="row">
    {% for cat in categories %}
        <div class="col s12 m6 l4">
            <a href="{{cat.category_slug}}", style="color:#000">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="card-title">{{cat.tutorial_category}}</div>
                        <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                        <p>{{cat.category_summary}}</p>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
</div>

<div class="sections">
    <button class="btn-large waves-effect waves-light red" >
        <a href="{% url 'mainApp:addCategory' %}" style="color:blanchedalmond ;">Add a new Category</a> 
    </button>
</div>

mainApp/templates/mainApp/includes/messages.html
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <script> M.toast({html: "{{message}}", 
                    classes: 'green rounded', displayLength:2000}) 
                </script>
            
            {% elif message.tags == 'info' %}
                <script> M.toast({html: "{{message}}", 
                    classes: 'blue rounded', displayLength:2000}) 
                </script>
            
            {% elif message.tag == 'warning' %}
                <script> M.toast({html: "{{message}}", 
                    classes: 'orange rounded', displayLength:2000}) 
                </script>
            
            {% elif message.tag == 'error' %}
                <script> M.toast({html: "{{message}}", 
                    classes: 'red rounded', displayLength:2000}) 
                </script>
            {% endif %}
        {% endfor %}
{% endif %}

mainApp/templates/mainApp/includes/navbar.html
{% load static %}
<div class="navbar-fixed">
  
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Tutorial</a>
      <form class="left" action="{% url 'mainApp:search' %}" method="GET" value="{{request.GET.q}}">
        <div class="input-field">
            <input type="text" id="searchInput" name="q" value="{{request.GET.q}}">
            <label class="label-icon" for="searchInput"><i class="material-icons">search</i>
            <i class="material-icons">close</i> </label>
        </div>
      </form>
      <a href="#!" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
            <li><a href="account/">{{user.username}}</a></li>
            <li><a href="{% url 'mainApp:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'mainApp:register' %}">Register</a></li>
            <li><a href="{% url 'mainApp:login' %}">Login</a></li>
        {% endif %}
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-trigger" href="#!" data-target="navDropdown">More<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
      
      
    </div>
  </nav>

</div>

<!-- Dropdown Structure -->
<ul id="navDropdown" class="dropdown-content">
  <li><a href="{% url 'mainApp:search' %}">Edit a Tutorial</a></li>
  <li><a href="{% url 'mainApp:search' %}">Delete a Tutorial</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>

<!-- always keep sidenav outise navar tags in materializecss framework-->
<ul id="slide-out" class="sidenav">
  <li><div class="user-view">
    <div class="background">
      <img src="{% static 'mainApp/images/random.jpg' %}">
    </div>
    <a href="#"><img class="circle" src="{% static 'mainApp/images/random.jpg' %}"></a>
    <a href="#"><span class="dark-text name">John Doe</span></a>
    <a href="#"><span class="dark-text email">jdandturk@gmail.com</span></a>
    </div>
  </li>
  <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
  <li><a href="/">Home</a></li>
  {% if user.is_authenticated %}
    <li><a href="account/">{{user.username}}</a></li>
    <li><a href="{% url 'mainApp:logout' %}">Logout</a></li>
  {% else %}
    <li><a href="{% url 'mainApp:register' %}">Register</a></li>
    <li><a href="{% url 'mainApp:login' %}">Login</a></li>
  {% endif %}
</ul>