mainApp/urls.py
from django.urls import path

from . import views

app_name = 'mainApp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('addTutorial/', views.add_new_tutorial, name='addTutorial'),
    path('addCategory/', views.add_new_tutorial_category, name='addCategory'),
    path('addSeries/', views.add_new_tutorial_series, name='addSeries'),
    path('search/', views.search, name='search'),
    path('<single_slug>', views.single_slug, name='single_slug'),
]

mainApp/models.py
from django.db import models
from datetime import datetime
# Create your models here.
# a model is creating a table in your database. So for each table one model class

class TutorialCategory(models.Model):
    tutorial_category = models.CharField(max_length=200)
    category_summary = models.CharField(max_length=200)
    category_slug = models.CharField(max_length=200, default=1)

    class Meta:
        # Gives the proper plural name for admin
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.tutorial_category

class TutorialSeries(models.Model):
    tutorial_series = models.CharField(max_length=200)
    series_summary = models.CharField(max_length=200)
    
    tutorial_category = models.ForeignKey(TutorialCategory,
                            default=1,
                            verbose_name="Category",
                            on_delete=models.SET_DEFAULT)
    

    class Meta:
        # otherwise we get "Tutorial Seriess in admin"
        verbose_name_plural = "Series"

    def __str__(self) -> str:
        return self.tutorial_series

class Tutorial(models.Model):
    tutorial_title = models.CharField(max_length=200)
    tutorial_content = models.TextField() 
    tutorial_published = models.DateTimeField('date published', default=datetime.now())

    tutorial_series = models.ForeignKey(TutorialSeries,
                            default=1,
                            verbose_name="Series",
                            on_delete=models.SET_DEFAULT)    

    tutorial_slug = models.CharField(max_length=200, default=1)

    def __str__(self) -> str:
        return self.tutorial_title

mainApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Tutorial, TutorialSeries, TutorialCategory

"""
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2",)

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
"""

class TutorialForm(forms.Form):    # We extends forms.ModelForm for easy form
    """
    tutorial_slug = forms.CharField(help_text="slug is a unique identifier for the tutorial")
    tutorial_content = forms.CharField(widget=TinyMCE(mce_attrs={'width': 100})
     )

    class Meta:
        model = Tutorial
        fields = ("tutorial_title", "tutorial_series", "tutorial_slug", "tutorial_content")
        
    """ 
    
    SERIES_CHOICES = [(obj , obj) for obj in TutorialSeries.objects.all()]
    title = forms.CharField()
    linked_series = forms.ChoiceField(choices=SERIES_CHOICES)
    content = forms.CharField()
    slug= forms.CharField(help_text='slug is a unique identifier for this tutorial')

    class Meta:
        model = Tutorial
        fields = ("tutorial_title", "tutorial_series", "tutorial_slug", "tutorial_content")


    def save(self, commit=True):
        
        tutorial = Tutorial()  #super(TutorialForm, self)
        tutorial.tutorial_title = self.cleaned_data["title"]
        # this filtering is needed because the choiceField is returning string and we need object
        tutorial.tutorial_series = TutorialSeries.objects.filter(tutorial_series = self.cleaned_data['linked_series'])[0]
        tutorial.tutorial_content = self.cleaned_data["content"]
        tutorial.tutorial_slug = self.cleaned_data["slug"]
        if commit:
            tutorial.save()
        return tutorial
    

class TutorialCategoryForm(forms.ModelForm):
    category_slug = forms.CharField(help_text="slug is a unique identifier for the category. It will be used for category url")

    class Meta:
        model = TutorialCategory
        fields = '__all__'


class TutorialSeriesForm(forms.ModelForm):

    class Meta:
        model = TutorialSeries
        fields = '__all__'

mainApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Tutorial, TutorialCategory, TutorialSeries
from django.db.models import Q
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import  TutorialForm, TutorialCategoryForm, TutorialSeriesForm
from django.contrib import messages
# Create your views here.
#A view function for a page
"""
def homepage(request):
    return HttpResponse('Hello you have started <strong>learning</strong> django framwork!!')
"""
#def single_slug()
def single_slug(request, single_slug):
    # first check to see if the url is in categories.

    categories = [c.category_slug for c in TutorialCategory.objects.all()]
    if single_slug in categories:
        matching_series = TutorialSeries.objects.filter(tutorial_category__category_slug=single_slug)
        series_urls = {}

        for m in matching_series.all():
            part_one = Tutorial.objects.filter(tutorial_series__tutorial_series=m.tutorial_series).earliest("tutorial_published")
            series_urls[m] = part_one.tutorial_slug

        return render(request=request,
                      template_name='mainApp/category.html',
                      context={"tutorial_series": matching_series, "part_ones": series_urls})

    tutorials = [t.tutorial_slug for t in Tutorial.objects.all()]
    if single_slug in tutorials:
        this_tutorial = Tutorial.objects.get(tutorial_slug = single_slug)
        tutorials_from_series = Tutorial.objects.filter(tutorial_series__tutorial_series = 
                                                this_tutorial.tutorial_series).order_by('tutorial_published')
        this_tutorial_index = list(tutorials_from_series).index(this_tutorial)

        return render(request,
                      template_name="mainApp/tutorial.html",
                      context={"tutorial":this_tutorial,
                               "sidebar": tutorials_from_series,
                               "this_tut_idx": this_tutorial_index}
        )

    return HttpResponse(f"'{single_slug}' does not correspond to anything we know of!")




def homepage(request):
    return render(request=request,
                template_name="mainApp/home.html",
                context={"categories": TutorialCategory.objects.all})


def add_new_tutorial(request):

    if request.method == "POST":
        form = TutorialForm(request.POST)
        if form.is_valid():
            tutorial = form.save()
            messages.info(request, f"Your tutorial #{tutorial.tutorial_title} is added")
            return redirect("mainApp:homepage")
        else:
            for msg in form.errors:
                messages.error(request, f"{msg}: {form.errors[msg]}")

    form = TutorialForm
    return render(request=request,
                template_name="mainApp/inputForms/addTutorial.html",
                context={"form": form }) 


def add_new_tutorial_category(request):

    if request.method == "POST":
        form = TutorialCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, f"Your tutorial Category is added")
            return redirect("mainApp:homepage")
        else:
            for msg in form.errors:
                messages.error(request, f"{msg}: {form.errors[msg]}")

    form = TutorialCategoryForm
    return render(request=request,
                template_name="mainApp/inputForms/addCategory.html",
                context={"form": form }) 


def add_new_tutorial_series(request):

    if request.method == "POST":
        form = TutorialSeriesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, f"Your tutorial series is added")
            return redirect("mainApp:homepage")
        else:
            for msg in form.errors:
                messages.error(request, f"{msg}: {form.errors[msg]}")

    form = TutorialSeriesForm
    return render(request=request,
                template_name="mainApp/inputForms/addSeries.html",
                context={"form": form }) 


def register(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Accoutn created successfully: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as: {username}")
            return redirect("mainApp:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")


    form = UserCreationForm
    return render(request=request,
                template_name="mainApp/register.html",
                context={"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully")
    return redirect("mainApp:homepage")


def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as: {username}")
                return redirect("mainApp:homepage")
            else:
                messages.error(request, f"Try again with a valid user credentials")
        else:
                messages.error(request, f"Try again with a valid user credentials")

    form = AuthenticationForm()
    return render(request=request,
                template_name="mainApp/login.html",
                context={"form":form})


def search(request):

    if request.method == "GET":
        query = request.GET.get('q')
        submitbutton = request.GET.get('submit')
        submitbutton = 'Search' # will be used if any search button is placed
        if query is not None:
            # create a custom lookup to be used for filter
            lookups = Q(tutorial_title__icontains=query) | Q(tutorial_content__icontains=query)
            results = Tutorial.objects.filter(lookups).distinct()
            # send matching objects to result page
            context={'results': results,
                     'submitbutton': submitbutton}
            if len(results)>0:
                messages.info(request, f"List of matched Tutorials")
            else:
                messages.warning(request, f"No results with searched title")
            return render(request,
                        template_name="mainApp/search.html",
                        context=context)
        else:
            messages.error(request, f"Provide a query to search")
            return render(request,
                        template_name="mainApp/search.html",)
    else:
        return render(request,
                        template_name="mainApp/search.html",)

mainApp/templates/mainApp/category.html
{% extends 'mainApp/header.html' %}

{% block content %}

    <div class="row">
        {% for tut, partone in part_ones.items %}

            <div class="col s12 m6 l4">
                <a href="{{partone}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{tut.tutorial_series}}</div>
                            <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                            <p>{{tut.series_summary}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <button class="btn-large waves-effect waves-light red" >
        <a href="{% url 'mainApp:addSeries' %}" style="color:blanchedalmond ;">Add a new tuorial series</a> 
    </button>
    
{% endblock %}

mainApp/templates/mainApp/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        
        <!-- Te purpose of header.html is it will contain the common objects from most pages
            eg. nav bar, footer, etc which they can extends
            It will not include any unique data of any page, 
            they will be placed where block content is specified
            on this page
        -->

        {% load static %}
        <link href="{% static 'tinymce/css/prism.css' %}" rel='stylesheet'/>

        <!-- Used for material design of your page from materializecss.com-->
        <!-- Compiled and minified CSS -->
        <link href="{% static 'mainApp/css/materialize.css' %}" rel='stylesheet'/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">  <!--link for materialized icons -->

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    </head>

    <body>
            
        {% include "mainApp/includes/navbar.html" %}
        
        <!-- the place where the unique content from child page will sit-->
        <div class="container">
            <br/>
            {% block content %}
            
            {%endblock%}
        </div>
    




        <!-- Common Scripts sections -->

            <!-- Compiled and minified JavaScript for materialize design -->
            <script src="{% static 'mainApp/js/bin/materialize.js' %}" ></script>
            
            <!-- Prism JS -->
            <script src="{% static 'tinymce/js/prism.js' %}"></script>

            <!-- Intialize all materializecss js with default values -->
            <script>M.AutoInit();</script>

            <!-- toast messages script-->
            {% include "mainApp/includes/messages.html" %}

            <!-- self defined js common for every page-->
            <script src="{% static 'mainApp/js/myjs/common.js' %}"></script>

        <!-- block for unique js of each page -->
        {% block js %}
            
        {%endblock%}
        
    </body>

    

</html>

mainApp/templates/mainApp/home.html
{% extends "mainApp/header.html" %}

{% load static %}

{% block content %}
    
    {% include "mainApp/includes/categories.html" %}

    <!-- This is the component to add floating button for several options -->
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large red">
            <i class="large material-icons">mode_edit</i>
        </a>
        <ul>
            <li>
                <a class="btn-floating tooltipped red" href="{% url 'mainApp:addCategory' %}" data-tooltip="add category"><i class="material-icons">insert_chart</i></a>
            </li>
            <li>
                <a class="btn-floating tooltipped yellow darken-1" href="{% url 'mainApp:addSeries' %}" data-tooltip="add series"><i class="material-icons">format_quote</i></a>
            </li>
            <li>
                <a class="btn-floating tooltipped green" href="{% url 'mainApp:addTutorial' %}" data-tooltip="add tutorial"><i class="material-icons">publish</i></a>
            </li>
            <li>
                <a class="btn-floating tooltipped blue" data-tooltip="I am a tooltip"><i class="material-icons">attach_file</i></a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'mainApp/js/myjs/home.js' %}"></script>
{% endblock %}

mainApp/templates/mainApp/login.html
{% extends "mainApp/header.html" %}


{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <button class="waves-effect waves-light btn" type="submit">login</button>
    </form>
    
    <p>If you don't already have an account, <a href="/register"><strong>register</strong></a> instead</p>

{% endblock %}

mainApp/templates/mainApp/register.html
{% extends "mainApp/header.html" %}


{% block content %}

    <h5 class='heading'>Please provide below required details for registration </h5>

    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{field.label}}
            {{field}}
            {{field.error }}
        {% endfor %}
        <button class="waves-effect waves-light btn" type="submit">register</button>
    </form>
    
    <p>If you already have an account, <a href="{% url 'mainApp:login' %}"><strong>login</strong></a> instead</p>

{% endblock %}

mainApp/templates/mainApp/search.html
{% extends "mainApp/header.html" %}

{% block content %}

    {% if submitbutton == 'Search' and request.GET.q != '' %}
        {% if results %}
            <h4>Results for <b>{{ request.GET.q }}</b></h4>
            
            <div class="row">
                {% for result in results %}

                <div class="col s12 m6 l4">
                    <a href="/{{result.tutorial_slug}}", style="color:#000">
                        <div class="card hoverable small">
                            <div class="card-content">
                                <div class="card-title">{{result.tutorial_title}}</div>
                                <p style="font-size:70%">Published: {{result.tutorial_published}}
                                <p>{{result.tutorial_content | safe}}</p>
                            </div>
                        </div>
                    </a>
                </div>

                {% endfor %}
            </div>
        {% else %}
            No search results for this query
        {% endif %}
    {% else %}
        Provide a query to search
    {% endif %}

{% endblock %}

mainApp/templates/mainApp/tutorial.html
{% extends "mainApp/header.html" %}

{% load static %}

{% block content %}
    <div class="row">   <!--class row specify that we are changing our view in terms of rows and colmns-->
        <div class="col s12 m8 l8">     <!-- it specifies no. of column to display on small, medium and large screen-->
                
            <h3>{{tut.tutorial_title}}</h3>
            <p style="font-size: 70%;">Published: {{ tutorial.tutorial_published }}</p>
            <p>{{ tutorial.tutorial_series }}</p>
            {{ tutorial.tutorial_content | safe }}

        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for tutorial in sidebar %}
                    {% if forloop.counter0 == this_tut_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{tutorial.tutorial_title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{tutorial.tutorial_title}}</div>
                            <div class="collapsible-body">
                                <p><a href="/{{tutorial.tutorial_slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
                        <li>
                            <br>
                            <div class="center-align">
                                <a href="{% url 'mainApp:addTutorial' %}">
                                    <button class="btn-floating btn-large waves-effect waves-light red" name="addTutorialBtn">
                                        <i class="material-icons">add</i>
                                    </button>
                                </a>    
                            </div>
                            <div class="center-align"><b>Add a new tutorial</b></div>
                        </li>
            </ul>
        </div>

    </div>
    
{% endblock %}


{% block js %}
    <script src="{% static 'mainApp/js/myjs/tutorial.js' %}"></script>
{% endblock %}